import type { Discovery } from "../engine/types";

interface Props {
  discoveries: Discovery[];
  onOpenReceipt: (id: string) => void;
  onOpenArchive: (focus: Discovery["archiveFocus"]) => void;
}

/**
 * The discoveries layer — "things you might have missed". Each card is
 * generated by the discovery engine from the archive, shows its evidence
 * inline (the traceable chain: discovery → evidence → receipts), and links
 * straight into the thread explorer or a filtered archive view.
 */
export default function Discoveries({ discoveries, onOpenReceipt, onOpenArchive }: Props) {
  if (discoveries.length === 0) return null;

  return (
    <section
      id="discoveries"
      aria-labelledby="discoveries-title"
      className="scroll-mt-16 border-t border-line py-24 sm:py-32"
    >
      <header className="mx-auto w-full max-w-6xl px-5 sm:px-8">
        <p className="label">Discoveries</p>
        <h2
          id="discoveries-title"
          className="mt-3 font-display text-4xl leading-[1.04] text-paper sm:text-5xl md:text-6xl"
        >
          Things you might have missed.
        </h2>
        <p className="mt-5 max-w-2xl text-sm leading-relaxed text-faded sm:text-base">
          Generated from the archive, not authored. Each card states the
          evidence it was surfaced from — follow it into the receipts.
        </p>
      </header>

      <div className="mx-auto mt-14 w-full max-w-6xl px-5 sm:px-8">
        <div className="rule grid gap-px bg-line md:grid-cols-2">
          {discoveries.map((d) => (
            <article key={d.id} className="bg-ink p-6 sm:p-7">
              <p className="label">
                <span className="mr-3 font-display text-lg italic text-mute">{d.numeral}</span>
                Discovery
              </p>
              <h3 className="mt-4 font-display text-2xl leading-tight text-accent sm:text-3xl">
                {d.title}
              </h3>
              <p className="mt-3 max-w-md text-sm leading-relaxed text-faded">{d.lead}</p>

              <dl className="mt-5 grid grid-cols-2 gap-x-6 gap-y-3">
                {d.evidence.map((e) => (
                  <div key={e.label} className="border-l border-line pl-3">
                    <dt className="label">{e.label}</dt>
                    <dd className="mt-0.5 text-sm text-paper">{e.value}</dd>
                  </div>
                ))}
              </dl>

              <div className="mt-6 flex flex-wrap gap-3">
                {d.receiptIds.length > 0 && (
                  <button
                    onClick={() => onOpenReceipt(d.receiptIds[0])}
                    className="border border-accent/70 px-4 py-2 text-[11px] uppercase tracking-[0.18em] text-accent transition-colors hover:bg-accent hover:text-ink"
                  >
                    Explore the thread →
                  </button>
                )}
                {d.archiveFocus && Object.keys(d.archiveFocus).length > 0 && (
                  <button
                    onClick={() => onOpenArchive(d.archiveFocus)}
                    className="border border-line px-4 py-2 text-[11px] uppercase tracking-[0.18em] text-faded transition-colors hover:border-accent hover:text-accent"
                  >
                    Open in archive
                  </button>
                )}
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}
